# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=20)),
                ('cast', models.PositiveIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, ''), (8, ''), (9, '')])),
                ('attributes', models.CommaSeparatedIntegerField(default='0,0,0,0,0,0,0,0,0', max_length=100)),
                ('skills', models.CharField(max_length=1200)),
                ('stuff', models.CharField(max_length=1200)),
                ('more', models.CharField(max_length=2500, null=True)),
            ],
        ),
    ]
