# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='cast',
            field=models.PositiveIntegerField(choices=[(1, 'Fongeux'), (2, 'Monteurs'), (3, 'Rapiats'), (4, 'Pisteurs')]),
        ),
    ]
