# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arach', '0002_auto_20160809_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archetype',
            name='uuid',
        ),
    ]
