# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arach', '0003_remove_archetype_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
