# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0002_auto_20160418_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='occup_cast',
            field=models.CharField(default='30,20,20,20', max_length=20),
        ),
        migrations.AlterField(
            model_name='path',
            name='occup_cast',
            field=models.CharField(default='30,20,20,20', max_length=20),
        ),
    ]
