# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 07:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0005_district_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='district',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='path',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='town',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
