# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 08:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0007_auto_20160418_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
