# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 08:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0008_auto_20160418_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
        ),
    ]
