# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0009_auto_20160418_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='occup_cast',
            field=models.CharField(default='40,20,20,20', max_length=20),
        ),
    ]
