# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0011_auto_20160418_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
