# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0012_auto_20160418_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='occup_cast',
            field=models.CharField(default='40,20,20,20', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='type_path',
            field=models.PositiveIntegerField(choices=[(1, 'Route'), (2, 'Rue'), (3, 'Chemin'), (4, 'Sentier'), (5, 'Pont'), (6, 'Ponton'), (7, 'Autre')], null=True),
        ),
    ]
