# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0015_remove_district_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='in_country',
        ),
        migrations.RemoveField(
            model_name='district',
            name='in_region',
        ),
        migrations.RemoveField(
            model_name='district',
            name='in_town',
        ),
        migrations.RemoveField(
            model_name='path',
            name='in_district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
