# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0016_auto_20160418_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('occup_cast', models.CharField(default='40,20,20,20', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('in_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.Country')),
                ('in_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.Region')),
                ('in_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.Town')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='in_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.District'),
        ),
    ]
