# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0017_auto_20160418_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='occup_cast',
            field=models.CharField(default='40,20,20,20', max_length=20, null=True),
        ),
    ]
