# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0018_auto_20160418_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='island',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('in_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.Country')),
                ('in_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primus.Region')),
            ],
        ),
    ]
