# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0020_island_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
