# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0021_auto_20160418_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='in_district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
