# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 06:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0024_auto_20160421_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='GridCentroid',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
