# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0025_grid_gridcentroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
