# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0026_auto_20160421_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='path',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='town',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='town',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='district',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='district',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='town',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='region',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
