# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 11:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0028_auto_20160424_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('type_street', models.PositiveIntegerField(choices=[(4, 'Rue'), (5, 'Ruelle'), (6, 'Pont'), (7, 'Ponton'), (8, 'Autre')], null=True)),
                ('allegiance', models.PositiveIntegerField(null=True)),
                ('region', models.PositiveIntegerField(null=True)),
                ('town', models.PositiveIntegerField(null=True)),
                ('district', models.PositiveIntegerField(null=True)),
                ('occup_cast', models.CharField(default='40,20,20,20', max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
            ],
        ),
        migrations.RemoveField(
            model_name='path',
            name='allegiance',
        ),
        migrations.RemoveField(
            model_name='path',
            name='district',
        ),
        migrations.RemoveField(
            model_name='path',
            name='occup_cast',
        ),
        migrations.RemoveField(
            model_name='path',
            name='region',
        ),
        migrations.RemoveField(
            model_name='path',
            name='town',
        ),
        migrations.AlterField(
            model_name='path',
            name='type_path',
            field=models.PositiveIntegerField(choices=[(1, 'Route'), (2, 'Chemin'), (3, 'Sentier')], null=True),
        ),
    ]
