# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0030_auto_20160525_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archetype',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='mal',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='pre',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='pui',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='res',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='sou',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='viv',
        ),
        migrations.RemoveField(
            model_name='archetype',
            name='vol',
        ),
        migrations.AddField(
            model_name='archetype',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='archetype',
            name='attributes',
            field=models.CommaSeparatedIntegerField(default='0,0,0,0,0,0,0,0', max_length=100),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='beauty',
            field=models.PositiveIntegerField(choices=[(0, 'Grande laideur'), (1, 'Classique'), (2, 'Grande Beauté')]),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='cast',
            field=models.PositiveIntegerField(choices=[(1, 'Gueux'), (2, 'Pègre'), (3, 'Popolo minuto'), (4, 'Popolo grasso'), (5, 'Clergé'), (6, 'Haut clergé'), (7, 'Haute bourgeoisie'), (8, "Noblesse d'épée"), (9, 'Noblesse de lettre')]),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Basique'), (2, 'Vétéran'), (3, 'Elite')]),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='heroism',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
