# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0032_archetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='more',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
