# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0034_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comm',
            field=models.CharField(default='Pouet', max_length=2000, null=True),
        ),
    ]
