# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0035_test_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPlace',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('origin', models.PositiveIntegerField(choices=[(1, 'Pays clémentin , Ravénie , Lombrie'), (2, 'Ostrie, Thémésie, Lagashein'), (3, 'Empire du Roi-Lune')])),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
