# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0036_assetplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetplace',
            old_name='used',
            new_name='use_count',
        ),
    ]
