# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0037_auto_20160531_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetplace',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
