# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0038_auto_20160531_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='type_street',
            field=models.PositiveIntegerField(choices=[(1, 'Avenue'), (2, 'Rue'), (3, 'Ruelle'), (4, 'Pont'), (5, 'Ponton')], null=True),
        ),
    ]
